name: Tests

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: Copy-Item config.example.json config.json
      - run: python -m pip install -r requirements.txt
      - run: python -m unittest -v test_creator
